#! /bin/bash
GPU_ID=$1

if [ -z "$GPU_ID" ]; then
    GPU_ID=0
fi

echo "Using GPU ID: $GPU_ID"

# my baseline: v2x-vit, intermediate fusion, classic delay compensation, 400ms delay (1-4 past frames)

echo "Evaluating v2x-vit with classic delay compensation (400ms delay) 1 len past"
#CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit --fusion_method 'intermediate' --name_output_result 'training_classic_delay400ms' --split_dataset 'training'
#CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit --fusion_method 'intermediate' --name_output_result 'validate_classic_delay400ms' --split_dataset 'validate'
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit --fusion_method 'intermediate' --name_output_result 'test_classic_delay400ms' --split_dataset 'test' --name_yaml config_evaluation_400ms.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit --fusion_method 'intermediate' --name_output_result 'test_classic_delay400ms_noRTE' --split_dataset 'test' --name_yaml config_evaluation_400ms_noRTE.yaml

if false; then
echo "Evaluating v2x-vit with 3DCNN block delay compensation (400ms delay) 2 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms --fusion_method 'intermediate' --name_output_result 'training_3dcnn_400ms_2past' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms/net_epoch76.pth'  --specific_epoch 76 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms --fusion_method 'intermediate' --name_output_result 'validate_3dcnn_400ms_2past' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms/net_epoch76.pth'  --specific_epoch 76 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms --fusion_method 'intermediate' --name_output_result 'test_mamba2_3dcnn_400ms_2past' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms/net_epoch76.pth'  --specific_epoch 76 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 3DCNN block delay compensation (400ms delay) 2 len past NO RTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_3dcnn_400ms_2past_noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_3dcnn_400ms_2past_noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2_3dcnn_400ms_2past_noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/3dcnn-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml

# MAMBA TRAININGS WITH 400MS DELAY (Not so fair because of no residual connections in the delay module)
echo "Evaluating v2x-vit with 2 MAMBA block delay compensation with residual connections (400ms delay) 2 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_2_res_400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_2_res_400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_2_res_400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 2 MAMBA block delay compensation with residual connections (400ms delay) 4 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_2_res_400ms_4past' --len_past 4 --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_2_res_400ms_4past' --len_past 4 --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_2_res_400ms_4past' --len_past 4 --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-2-residual/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 MAMBA block delay compensation with residual connections (400ms delay) 2 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_1_res_400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_1_res_400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_1_res_400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 3 MAMBA block delay compensation with residual connections (400ms delay) 2 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_3_res_400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms/net_epoch86.pth'  --specific_epoch 86 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_3_res_400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms/net_epoch86.pth'  --specific_epoch 86 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_3_res_400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms/net_epoch86.pth'  --specific_epoch 86 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 3 MAMBA block delay compensation with residual connections (400ms delay) 4 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_3_4p_400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml --len_past 4
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_3_4p_400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml --len_past 4
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_3_4p_400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml --len_past 4

echo "NOW WITH 2 len past"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'training_mamba2_encoding_cls_3_2p_400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'validate_mamba2_encoding_cls_3_2p_400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past --fusion_method 'intermediate' --name_output_result 'test_mamba2_encoding_cls_3_2p_400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamaba2-encoding-cls-3-4past/net_epoch75.pth'  --specific_epoch 75 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 3 MAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE --fusion_method 'intermediate' --name_output_result 'training_mamba2-encoding-cls-3-400ms-4past-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE/net_epoch68.pth'  --specific_epoch 68 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE --fusion_method 'intermediate' --name_output_result 'validate_mamba2-encoding-cls-3-400ms-4past-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE/net_epoch68.pth'  --specific_epoch 68 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2-encoding-cls-3-400ms-4past-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-3-400ms-4past-noRTE/net_epoch68.pth'  --specific_epoch 68 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 MAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_mamba2-encoding-cls-1-400ms-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_mamba2-encoding-cls-1-400ms-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2-encoding-cls-1-400ms-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-encoding-cls-1-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml
echo "Evaluating v2x-vit with 1 MAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_mamba2-256-encoding-cls-1-1drop-400ms-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_mamba2-256-encoding-cls-1-1drop-400ms-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2-256-encoding-cls-1-1drop-400ms-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-1-1drop-400ms-noRTE/net_epoch78.pth'  --specific_epoch 78 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 MAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_mamba2-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_mamba2-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch72.pth'  --specific_epoch 72 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 MAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch80.pth'  --specific_epoch 80 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch80.pth'  --specific_epoch 80 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/mamba2-noisyloc-256-encoding-cls-3-1drop-400ms-noRTE/net_epoch80.pth'  --specific_epoch 80 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 biMAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'training_bimamba2-encoding-cls-1-400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'validate_bimamba2-encoding-cls-1-400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms --fusion_method 'intermediate' --name_output_result 'test_bimamba2-encoding-cls-1-400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-1-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 biMAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms --fusion_method 'intermediate' --name_output_result 'training_bimamba2-encoding-cls-2-400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms --fusion_method 'intermediate' --name_output_result 'validate_bimamba2-encoding-cls-2-400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms --fusion_method 'intermediate' --name_output_result 'test_bimamba2-encoding-cls-2-400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-2-400ms/net_epoch70.pth'  --specific_epoch 70 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 biMAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'training_bimamba2-encoding-cls-3-400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'validate_bimamba2-encoding-cls-3-400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms --fusion_method 'intermediate' --name_output_result 'test_bimamba2-encoding-cls-3-400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms/net_epoch65.pth'  --specific_epoch 65 --name_yaml config_training_hypes.yaml


echo "Evaluating v2x-vit with 1 biMAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms --fusion_method 'intermediate' --name_output_result 'training_bimamba2-encoding-cls-dropout-2-400ms' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms/net_epoch85.pth'  --specific_epoch 85 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms --fusion_method 'intermediate' --name_output_result 'validate_bimamba2-encoding-cls-dropout-2-400ms' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms/net_epoch85.pth'  --specific_epoch 85 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms --fusion_method 'intermediate' --name_output_result 'test_bimamba2-encoding-cls-dropout-2-400ms' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-dropout-2-400ms/net_epoch85.pth'  --specific_epoch 85 --name_yaml config_training_hypes.yaml

echo "Evaluating v2x-vit with 1 biMAMBA block delay compensation with residual connections (400ms delay) 4 len past noRTE"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'training_bimamba2-encoding-cls-3-400ms-noRTE' --split_dataset 'training' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'validate_bimamba2-encoding-cls-3-400ms-noRTE' --split_dataset 'validate' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE --fusion_method 'intermediate' --name_output_result 'test_bimamba2-encoding-cls-3-400ms-noRTE' --split_dataset 'test' --module_delay  --specific_path 'MODEL_v2xset/v2x-vit/TRAININGS/bimamba2-encoding-cls-3-400ms-noRTE/net_epoch74.pth'  --specific_epoch 74 --name_yaml config_training_hypes.yaml

# MAMBA TRAININGS WITH 400MS DELAY (Not so fair because of no residual connections in the delay module)
EPOCH=76
TITLE="mamba2-768-huber-encoding-cls-3-400ms-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=72
TITLE="mamba2-768-huber-encoding-cls-3-400ms-2drop-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=78
TITLE="bimamba2-768-smoothl1-encoding-cls-3-400ms-2drop-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=80
TITLE="mamba2-768-smoothl1-encoding-cls-3-400ms-2drop-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=68
TITLE="mamba2-768-smoothl1-encoding-cls-3-400ms-16patch-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=72
TITLE="mamba2-freezedheads-encoding-cls-1-0drop-400ms-4past-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml --len_past 4
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml --len_past 4
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml --len_past 4

EPOCH=72
TITLE="mamba2-768-nodelayloss-encoding-cls-3-400ms-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml

EPOCH=68
TITLE="mamba2-256-nodelayloss-encoding-cls-3-400ms-noRTE"
echo "Evaluating ${TITLE}"
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "training_$TITLE_$EPOCH" --split_dataset 'training' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "validate_$TITLE_$EPOCH" --split_dataset 'validate' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth  --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
CUDA_VISIBLE_DEVICES=$GPU_ID python opencood/tools/inference.py --model_dir MODEL_v2xset/v2x-vit/TRAININGS/$TITLE --fusion_method 'intermediate' --name_output_result "test_$TITLE_$EPOCH" --split_dataset 'test' --module_delay  --specific_path MODEL_v2xset/v2x-vit/TRAININGS/$TITLE/net_epoch${EPOCH}.pth --specific_epoch $EPOCH --name_yaml config_training_hypes.yaml
fi